version: '3'
services:
  frontend:
    image: kwarc/mws-frontend
    ports: 
      - 8080:80
    networks:
      - default
      - internal

  mws:
    image: kwarc/mathwebsearch
    volumes:
      - harvests:/data/
    networks:
      - internal

volumes:
  harvests:

networks:
  internal: